### ISSUE TITLE
I deleted my online repository for WB-India by mistake

### ISSUE THREAD

**Issue by dddodums** [OpenRG/WB-India-2019#31]
Hi Jason/Rick,

I mistakenly deleted my online WB-India repository. It is empty now. I have attached how it looks. Can you please help. Thank you.

Best,

Sana
![Capture](https://user-images.githubusercontent.com/46542159/63885689-e974a280-c9a6-11e9-9f79-2b96a83a3cbd.PNG)

**Comment by jdebacker** [comment]
@dddodums, I think you should be able to fix this with the following steps:

1. In your command line, navigate to your `WB-India-2019` directory.
2. Type `git checkout master` to be sure you are on the master branch.
3. Type `git status -uno` to see if you have any uncommitted changes.  If you do, type `git stash`, if you don't, proceed to the next step.
4. Type `git fetch upstream`
5. Type `git merge upstream/master`
6. Type `git push origin master`

After step 6, check your remote repository (https://github.com/dddodums/WB-India-2019) and it should match the https://github.com/OpenRG/WB-India-2019 repository.

**Comment by dddodums** [comment]
No Jason,

It is still empty:(. It did not work.

Actually I wanted to delete and reclone my wb-india on my local computer but it wouldn't let me so I typed the following commands:

**In the command-line, navigate to your local repository.
Ensure you are in the default branch:
git checkout master
The rm -r command will recursively remove your folder:
git rm -r folder-name
Commit the change:
git commit -m "Remove duplicated directory"
Push the change to your remote repository:
git push origin master**

And it made it empty.

**Comment by dddodums** [comment]
Is there anything else I can try?
Can I delete the repository and fork again?

**Comment by jdebacker** [comment]
@dddodums , yes, you can delete and clone again.  But I just went to your remote fork and all the files are there - so it looks like you fixed things.  Great job!  If everything is resolved, please comment on that here and close this issue.

**Comment by dddodums** [comment]
Yes, thank you!
