### ISSUE TITLE
TEST: Bad first paragraph

### ISSUE THREAD

**Issue by rickecon** [OpenRG/WB-India-2019#6]
Jason and Rick do not think the first paragraph on the `README.md` file is very good.

> This repository contains the training materials, tutorials, lecture notes, code, and problem sets for the World Bank sponsored training of TPRU staff in Delhi, India August 5-9 and August 19-23. The training will be lead by Dr. Richard W. Evans, Associate Director and Senior Lecturer at the University of Chicago M.A. Program in Computational Social Science and Dr. Jason DeBacker, Associate Professor in the Department of Economics at the University of South Carolina.

Please submit a pull request with suggested changes.

**Comment by com1tpru** [comment]
I think it is quite OK. @rickecon @jdebacker

**Comment by indira-tpru** [comment]
This repository contains the training materials, tutorials, lecture notes, code, and problem sets for the World Bank sponsored training of TPRU staff in Delhi, India August 5-9 and August 19-23. We need to be in sync with pythons, anacondas and spiders as we embark on this wonderful ride !

 The training will be lead by Dr. Richard W. Evans, Associate Director and Senior Lecturer at the University of Chicago M.A. Program in Computational Social Science and Dr. Jason DeBacker, Associate Professor in the Department of Economics at the University of South Carolina.

**Comment by rickecon** [comment]
@shekharkhetan, do you think we should use humor in this first paragraph?

**Comment by sktpru** [comment]
yes we can

**Comment by rickecon** [comment]
@indira-tpru. Thanks for that suggestion. I would love to see a pull request.

**Comment by rickecon** [comment]
@sktpru, who is this. I like your enthusiasm.

**Comment by shekharkhetan** [comment]
@rickecon Yes we should I think Professor. :)
